% AFFC.m
% Main function for the Analytical Flow Forming Contact calculator
% Creates/ends main interaction GUI
% Calls calculation subroutines plot2Dsol.m, plot3Dsol.m, 
% ToolContactArea.m, ToolContactPointCloudWrite.m
% Activates interaction subroutines
% M.J. Roy, 2016
function AFFC

sz=[1000 600];
screensize=get(0,'ScreenSize');
xpos = ceil((screensize(3)-sz(1))/2); % centre the figure on the screen horizontally
ypos = ceil((screensize(4)-sz(2))/2); % centre the figure on the screen vertically
startWinSize=[xpos ypos sz(1) sz(2)];
scaleVal=[sz sz];
warning off;
mainwindow=figure('Visible','on','Name','Analytical Flow Forming Contact Calculator','NumberTitle','off',...
    'Position',startWinSize,...
    'MenuBar','none','Color','white',...
    'CloseRequestFcn',@fig_CloseDeleteMain);

panelAx = uipanel('Parent',mainwindow,'Title','','Position',[1 0 1 1],...
           'BackgroundColor','white');

pushbutton_Update = uicontrol(mainwindow,'Style','pushbutton',...
            'String','<html><b>Update<html>',...
           'Position',[10 22 60 30]./scaleVal,...
           'units','normalized','fontunits','normalized',...
           'Callback',@pushbutton_UpdateCallback,'keypressfcn',@RetKP);

togglebutton_Rotate = uicontrol(mainwindow,'Style','togglebutton','String','Rotate',...
           'Position',[360 22 60 30]./scaleVal,...
           'units','normalized','fontunits','normalized',...
           'Callback',@togglebutton_RotateCallback);

togglebutton_Pan = uicontrol(mainwindow,'Style','togglebutton','String','Pan',...
           'Position',[420 22 60 30]./scaleVal,...
           'units','normalized','fontunits','normalized',...
           'Callback',@togglebutton_PanCallback);

togglebutton_Zoom = uicontrol(mainwindow,'Style','togglebutton','String','Zoom',...
           'Position',[480 22 60 30]./scaleVal,...
           'units','normalized','fontunits','normalized',...
           'Callback',@togglebutton_ZoomCallback);
       
togglebutton_DCursor = uicontrol(mainwindow,'Style','togglebutton','String','Data Cursor',...
           'Position',[640 22 100 30]./scaleVal,...
           'units','normalized','fontunits','normalized',...
           'Callback',@togglebutton_DCursorCallback);       

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Label uicontrols for labels
Label.I(1)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b>R<sub>m</sub></html>',...
           'Position',[10 560 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label1Callback);

Label.I(2)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b>t<sub>o</sub></html>',...
           'Position',[10 530 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label2Callback);
       
Label.I(3)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b>t<sub>f</sub></html>',...
           'Position',[10 500 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label3Callback);
       
Label.I(4)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b>R<sub>r</sub></html>',...
           'Position',[10 470 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label4Callback);

Label.I(5)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b>R</html>',...
           'Position',[10 440 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label5Callback);

Label.I(6)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b><i>a</html>',...
           'Position',[10 410 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label6Callback);      

Label.I(7)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b><i>b</html>',...
           'Position',[10 380 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label7Callback);       
       
Label.I(8)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b>P</html>',...
           'Position',[10 350 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label8Callback); 

Label.I(9)=uicontrol(mainwindow,'style','togglebutton','string',...
    '<html><b>R<sup>*</sup></html>',...
           'Position',[10 290 28 30]./scaleVal,'FontSize',10,...
           'units','normalized','fontunits','normalized',...
           'ForegroundColor','black',...
           'BackgroundColor',get(mainwindow,'color'),'visible','on',...
           'Callback',@togglebutton_Label9Callback);

%Radio button uicontrols
rb_edges=uicontrol(mainwindow,'Style','RadioButton','String',...
            '<html><b>Edges<html>',...
            'Position',[10 230 60 20]./scaleVal,'Fontsize',10,...
            'units','normalized','fontunits','normalized',...
            'BackgroundColor',get(mainwindow,'color'),'visible','on',...
            'value',0);
rb_Area=uicontrol(mainwindow,'Style','RadioButton','String',...
            '<html><b>Calculate area<html>',...
            'Position',[10 120 120 20]./scaleVal,'Fontsize',10,...
            'units','normalized','fontunits','normalized',...
            'BackgroundColor',get(mainwindow,'color'),'visible','on',...
            'value',0);        
rb_Out=uicontrol(mainwindow,'Style','RadioButton','String',...
            '<html><b>Write points<html>',...
            'Position',[10 100 120 20]./scaleVal,'Fontsize',10,...
            'units','normalized','fontunits','normalized',...
            'BackgroundColor',get(mainwindow,'color'),'visible','on',...
            'value',0);
        
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Text input boxes uicontrols       
I.val(1)= uicontrol(mainwindow,'Style','edit','String',...
            '69.33','Position',[42 568 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);       

I.val(2)= uicontrol(mainwindow,'Style','edit','String',...
            '8.05','Position',[42 538 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);    

I.val(3)= uicontrol(mainwindow,'Style','edit','String',...
            '6.17','Position',[42 508 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);    

I.val(4)= uicontrol(mainwindow,'Style','edit','String',...
            '56.23','Position',[42 478 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);     
        
I.val(5)= uicontrol(mainwindow,'Style','edit','String',...
            '5','Position',[42 448 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);            
       
I.val(6)= uicontrol(mainwindow,'Style','edit','String',...
            '45','Position',[42 418 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);    
        
I.val(7)= uicontrol(mainwindow,'Style','edit','String',...
            '60','Position',[42 388 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);    

I.val(8)= uicontrol(mainwindow,'Style','edit','String',...
            '2.54','Position',[42 358 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);    

I.val(9)= uicontrol(mainwindow,'Style','edit','String',...
            '60','Position',[42 298 60 20]./scaleVal,'FontSize',11,...
            'units','normalized','fontunits','normalized',...
            'HorizontalAlignment','left','BackgroundColor','white',...
            'ForegroundColor','black','keypressfcn',@RetKP);            

%Information push button that brings up a message box
pushbutton_Info = uicontrol(mainwindow,'Style','pushbutton',...
            'String','About','position',...
           [0.9555 .97 0.045 0.03],'HorizontalAlignment',...
           'right','FontSize',8,'ForegroundColor','black',...
           'units','normalized','fontunits','normalized',...
           'BackgroundColor',get(mainwindow,'color'),...
           'Callback',@pushbutton_InfoCallback);

%String relating version number
text_Ver=uicontrol(mainwindow,'Style','text','String','ver 1.0',...
           'Position',[0.9555 0.95 0.045 0.0188],'HorizontalAlignment',...
           'center','FontSize',8,'ForegroundColor','black',...
           'units','normalized','fontunits','normalized',...
           'BackgroundColor',get(mainwindow,'color'));

%close function, closes everything in anger
function fig_CloseDeleteMain(varargin)
         close all force
end

%string for the info box
infoBoxStrings={'This application was written by M.J. Roy to visualize the solution technique described in:\n'... 
    '"Analytical solution of the tooling/workpiece contact interface shape during a flow forming operation" ' ...
    ' by M.J. Roy, D.M. Maijer, Robert J. Klassen, J.T. Wood and E. Schost,' ...
    ' published in the Journal of Materials Processing Technology (Volume 210, Issue 14, 1 November 2010)\n ' ...
    'http://dx.doi.org/10.1016/j.jmatprotec.2010.07.011\narXiv:1206.2547\n'...
    'Please review the documentation for further information and permissions.\n'...
    'Attribution-ShareAlike, CC BY-SA.  M.J. Roy 2013-16, some rights reserved.'};

%write the textbox
function pushbutton_InfoCallback(varargin)
    hInfo=msgbox(sprintf(strcat(infoBoxStrings{1},'\n',infoBoxStrings{2},...
        infoBoxStrings{3}, infoBoxStrings{4},'\n',infoBoxStrings{5},'\n',...
        infoBoxStrings{6},infoBoxStrings{7})),'About this application');
end

%functions and subfunctions to run when 'Update' is pressed.
function ExecuteOnUpdate
    Ex=str2double(get(I.val(1:9),'string'));
    %get options
    Ed=get(rb_edges,'value');
    Acalc=get(rb_Area,'value');
    PointCloudOutput=get(rb_Out,'value');
    
    h1=subplot(121);
    h1Pos=get(h1,'position');
    set(h1,'Position',[h1Pos(1)+.05 h1Pos(2)+.05 h1Pos(3:4)]);
    [zees]=plot2Dsol(Ex,Ed);
    view(2);
    axis(h1,'equal');
    
    h2=subplot(122);
    h2Pos=get(h2,'position');
    set(h2,'Position',[h2Pos(1)+.05 h2Pos(2)+.05 h2Pos(3:4)]);
    [x,y,z]=plot3Dsol(Ex,zees,Ed);
    view(0,0)
    axis(h2,'equal')

    if Acalc
        ToolContactArea(x,y,z);
    end
    if PointCloudOutput
        ToolContactPointCloudWrite(x,y,z);
    end
end

function pushbutton_UpdateCallback(varargin)
    ExecuteOnUpdate;
end

function RetKP(varargin) %if return key pressed
    if strcmp(varargin{2}.Key,'return')
        ExecuteOnUpdate;
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%labels and placement for text box descriptors
Desc={'Mandrel radius' 'Starting material thickness'...
    'Final material thickness' 'Roller radius excluding nose radius'...
    'Roller nose radius' 'Entry or attack angle (°)' ...
    'Exit or planishing angle (°)' 'Tool pitch' 'Resolution'};
for J=1:9
    LabelTagPos=get(Label.I(J),'Position');
    LabelTagPos=LabelTagPos+[25 0 210 0]./scaleVal;
    Tbox(J)=uicontrol('style','text','Position',LabelTagPos,...
    'Fontsize',11,'units','normalized','fontunits','normalized',...
    'visible','off','string',Desc{J},'HorizontalAlignment','left');
end
%Handle label descriptions, (visible vs. invisible)
function togglebutton_Label1Callback(varargin)
    ToggleValue=get(Label.I(1),'Value');
    if ToggleValue
        set(Tbox(1),'visible','on')        
    else
        set(Tbox(1),'visible','off')
    end
end

function togglebutton_Label2Callback(varargin)
    ToggleValue=get(Label.I(2),'Value');
    if ToggleValue
        set(Tbox(2),'visible','on')        
    else
        set(Tbox(2),'visible','off')
    end
end

function togglebutton_Label3Callback(varargin)
    ToggleValue=get(Label.I(3),'Value');
    if ToggleValue
        set(Tbox(3),'visible','on')        
    else
        set(Tbox(3),'visible','off')
    end
end

function togglebutton_Label4Callback(varargin)
    ToggleValue=get(Label.I(4),'Value');
    if ToggleValue
        set(Tbox(4),'visible','on')        
    else
        set(Tbox(4),'visible','off')
    end
end

function togglebutton_Label5Callback(varargin)
    ToggleValue=get(Label.I(5),'Value');
    if ToggleValue
        set(Tbox(5),'visible','on')        
    else
        set(Tbox(5),'visible','off')
    end
end

function togglebutton_Label6Callback(varargin)
    ToggleValue=get(Label.I(6),'Value');
    if ToggleValue
        set(Tbox(6),'visible','on')        
    else
        set(Tbox(6),'visible','off')
    end
end

function togglebutton_Label7Callback(varargin)
    ToggleValue=get(Label.I(7),'Value');
    if ToggleValue
        set(Tbox(7),'visible','on')        
    else
        set(Tbox(7),'visible','off')
    end
end

function togglebutton_Label8Callback(varargin)
    ToggleValue=get(Label.I(8),'Value');
    if ToggleValue
        set(Tbox(8),'visible','on')        
    else
        set(Tbox(8),'visible','off')
    end
end

function togglebutton_Label9Callback(varargin)
    ToggleValue=get(Label.I(9),'Value');
    if ToggleValue
        set(Tbox(9),'visible','on')        
    else
        set(Tbox(9),'visible','off')
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%turn on/off rotation
function togglebutton_RotateCallback(varargin)
    ToggleValue=get(togglebutton_Rotate,'Value');
    if ToggleValue
        set(togglebutton_Zoom,'Value',0);
        set(togglebutton_Pan,'Value',0);
        set(togglebutton_DCursor,'Value',0);
        rotate3d on;
    else
    rotate3d off
    end
end

%turn on/off panning
function togglebutton_PanCallback(varargin)
    ToggleValue=get(togglebutton_Pan,'Value');
    if ToggleValue
        set(togglebutton_Zoom,'Value',0);
        set(togglebutton_Rotate,'Value',0);
        set(togglebutton_DCursor,'Value',0);
        pan on;        
    else
        pan off
    end
end

%turn on/off zooming
function togglebutton_ZoomCallback(varargin)
    ToggleValue=get(togglebutton_Zoom,'Value');
    if ToggleValue
        set(togglebutton_Rotate,'Value',0);
        set(togglebutton_Pan,'Value',0);
        set(togglebutton_DCursor,'Value',0);
        zoom on;
    else
        zoom off
    end
end

%turn on/off data cursor
function togglebutton_DCursorCallback(varargin)
    ToggleValue=get(togglebutton_DCursor,'Value');
    if ToggleValue
        set(togglebutton_Rotate,'Value',0);
        set(togglebutton_Pan,'Value',0);
        set(togglebutton_Zoom,'Value',0);
        datacursormode on
    else
        delete(findall(gcf,'Type','hggroup'));
        datacursormode off
    end
end


end